version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - secret.env
    environment:
      - POSTGRES_DB=oddities_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      # ВАЖНО: Тут данные должны совпадать с тем, что в блоке db выше
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/oddities_db
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A Oddities worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/oddities_db
    depends_on:
      - redis
      - db

  tg_bot:
    build: ./tg_bot
    command: python bot_main.py
    volumes:
      - ./tg_bot:/app
      # Пробрасываем папку для базы бота, чтобы sqlite мог создать файл
      - ./tg_bot/bot_db:/app/bot_db
    working_dir: /app
    env_file:
      - secret.env
    depends_on:
      - web
      - db

volumes:
  postgres_data: